trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool

variables:
  deployPath: /var/www/html

steps:
- checkout: self

# Copy website files to VM
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ubuntu-nginx-ssh'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      **
    targetFolder: '$(deployPath)'
    cleanTargetFolder: true
    overwrite: true

# Restart nginx + verify deployment
- task: SSH@0
  inputs:
    sshEndpoint: 'ubuntu-nginx-ssh'
    runOptions: 'commands'
    commands: |
      sudo systemctl restart nginx
      echo "===== FILES DEPLOYED ====="
      ls -la /var/www/html